---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: trustification
spec:
  displayName: trustification
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: trustification-guac
  annotations:
    build.appstudio.openshift.io/request: configure-pac
    image.redhat.com/generate: '{"visibility": "private"}'
spec:
  application: trustification
  componentName: trustification-guac
  source:
    git:
      revision: trustification-main
      devfileUrl: https://raw.githubusercontent.com/devfile-samples/devfile-sample-go-basic/main/devfile.yaml
      url: https://github.com/trustification/guac
      dockerfileUrl: dockerfiles/Dockerfile.guac-ubi
      context: ./
